name: Build Flutter APK file

on:

  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
          cache: true
          flutter-version: '3.35.1'

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Run pub get
        run: flutter pub get

      - name: Run unit tests
        run: flutter test
      - name: Extract version info from pubspec
        shell: bash
        run: |
          set -e
          LINE=$(grep '^version:' pubspec.yaml | head -1)
          VERSION_NAME=$(echo "$LINE" | sed -E 's/version:\s*([0-9.]+)\+.*/\1/')
          C=$(echo "$LINE" | sed -E 's/.*\+([0-9]+).*/\1/')    # %c
          
          # base per-ABI build numbers (what we pass to --build-number)
          BASE11=$(( C*10 + 1 ))
          BASE12=$(( C*10 + 2 ))
          BASE13=$(( C*10 + 3 ))
          
          echo "VERSION_NAME=$VERSION_NAME"           >> $GITHUB_ENV
          echo "BASE11=$BASE11"                       >> $GITHUB_ENV
          echo "BASE12=$BASE12"                       >> $GITHUB_ENV
          echo "BASE13=$BASE13"                       >> $GITHUB_ENV

      - name: Build split APKs (use base numbers)
        shell: bash
        run: |
          set -e
          flutter build apk --release --split-per-abi --target-platform=android-x64   --build-number=${BASE11}
          flutter build apk --release --split-per-abi --target-platform=android-arm   --build-number=${BASE12}
          flutter build apk --release --split-per-abi --target-platform=android-arm64 --build-number=${BASE13}
          flutter build apk --release

      - name: Rename APKs
        run: |
          cd build/app/outputs/flutter-apk
          mv app-armeabi-v7a-release.apk Gpa-Calculator-${GITHUB_REF_NAME}-armeabi-v7a.apk
          mv app-arm64-v8a-release.apk Gpa-Calculator-${GITHUB_REF_NAME}-arm64-v8a.apk
          mv app-x86_64-release.apk Gpa-Calculator-${GITHUB_REF_NAME}-x86_64.apk
          mv app-release.apk Gpa-Calculator-${GITHUB_REF_NAME}-universal.apk

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          allowUpdates: true
          token: ${{ secrets.PAT_TOKEN }}
